# Generated by Django 5.1.4 on 2025-05-14 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('policy_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('booking_type', models.CharField(max_length=20)),
                ('days_before_event', models.IntegerField()),
                ('refund_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CateringService',
            fields=[
                ('catering_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50, unique=True)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('discount_name', models.CharField(max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('event_date', models.DateField()),
                ('total_hours', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_canceled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall_app.discount')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('cancellation_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cancellation_date', models.DateField()),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancellation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hall_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('feedback_date', models.DateField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hall_app.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hall_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hall_app.hall')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('request_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('issue_description', models.TextField()),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('resolved', 'Resolved')], max_length=20)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('notification_date', models.DateField()),
                ('notification_type', models.CharField(choices=[('booking', 'Booking'), ('cancellation', 'Cancellation'), ('reminder', 'Reminder'), ('feedback', 'Feedback')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hall_app.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('credit card', 'Credit Card'), ('debit card', 'Debit Card'), ('upi', 'UPI'), ('cash', 'Cash'), ('net banking', 'Net Banking')], max_length=20)),
                ('payment_status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.booking')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall_app.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('contact_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('catering', 'Catering'), ('maintenance', 'Maintenance')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('staff', 'Staff')], default='customer', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingCatering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.booking')),
                ('catering_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.cateringservice')),
            ],
            options={
                'unique_together': {('booking', 'catering_service')},
            },
        ),
        migrations.CreateModel(
            name='HallAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.amenity')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.hall')),
            ],
            options={
                'unique_together': {('hall', 'amenity')},
            },
        ),
        migrations.CreateModel(
            name='HallStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.hall')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_app.staff')),
            ],
            options={
                'unique_together': {('hall', 'staff')},
            },
        ),
    ]
