# Generated by Django 5.1.4 on 2025-05-15 04:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallimage',
            name='id',
        ),
        migrations.AddField(
            model_name='hall',
            name='address',
            field=models.CharField(default='Address to be updated', max_length=255),
        ),
        migrations.AddField(
            model_name='hall',
            name='contact_number',
            field=models.CharField(default='Not provided', max_length=15),
        ),
        migrations.AddField(
            model_name='hall',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hall',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hallimage',
            name='image_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='hallimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amenity',
            name='amenity_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='amenity_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hall',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hallamenity',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_amenities', to='hall_app.hall'),
        ),
        migrations.AlterField(
            model_name='hallamenity',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
